### ISSUE TITLE
How do you run/start  this

### ISSUE THREAD

**Issue by justnothi** [michaelshumshum/skribbl-spambot-template#1]

**Comment by justnothi** [comment]
?

**Comment by michaelshumshum** [comment]
read the readme. 

get python. install all the packages needed. change the messages and run "bot.py". 

if you don't know what i am talking about, then you shouldn't be getting into this. go learn basic python before you set this up.

**Comment by justnothi** [comment]
just tell me how to run bot.py

**Comment by justnothi** [comment]
like what command is it
?

**Comment by michaelshumshum** [comment]
"python3 bot.py"

this is the last piece of help you get from me. you are on your own.

**Comment by justnothi** [comment]
ok
