### ISSUE TITLE
Traceback (most recent call last):   File "C:\Downloads\skribbl-spambot-template-main\skribbl-spambot-template-main\bot.py", line 1, in <module>     import pyppeteer ModuleNotFoundError: No module named 'pyppeteer'

### ISSUE THREAD

**Issue by justsomerandomkname** [michaelshumshum/skribbl-spambot-template#2]
Traceback (most recent call last):
  File "C:\Downloads\skribbl-spambot-template-main\skribbl-spambot-template-main\bot.py", line 1, in <module>
    import pyppeteer
ModuleNotFoundError: No module named 'pyppeteer'  **But i have the module, all of them.**

**Comment by michaelshumshum** [comment]
are you using pycharm or any IDE? do you have any other versions of python installed? in some cases, pip installs python packages in the wrong python directory.

**Comment by michaelshumshum** [comment]
this isnt a problem with my script. it's probably a python configuration issue that can be solved with a few google searches.
